---
apiVersion: v1
kind: Service
metadata:
  name: service-vproapp
spec:
  ports:
  - port: 8090
    nodePort: 30021
    targetPort: 8080
    protocol: TCP 
  selector:
    app: vproapp
  type: NodePort
